---
title: Create table of TPMAs with zero mitigation
lang: en-GB
embed-resources: true
minimal: true
code-fold: true
params:
  rds_filename: zero_mitigation_data
---

```{r}
#| label: setup
rds_fname <- sub("(\\.rds)+$", ".rds", paste0(params[["rds_filename"]], ".rds"))
```
```{r}
#| label: get source data from Azure

az_token <- azkit::get_auth_token()
support_con_name <- Sys.getenv("AZ_SUPPORT_CONTAINER")

tpma_data <- azkit::get_container(support_con_name, token = az_token) |>
  azkit::read_azure_csv("mitigator-lookup.csv", col_types = "ccc------") |>
  dplyr::rename(
    type = "activity_type",
    change_factor = "mitigator_type",
    strategy = "mitigator_variable"
  )
```

```{r}
#| label: prepare data list

zero_mitigation_tpma_data <- tpma_data |>
  dplyr::mutate(
    dplyr::across("type", \(x) forcats::fct(x, c("ip", "op", "aae"))),
    dplyr::across("strategy", \(x) {
      sub("^ambulatory_emergency", "same_day_emergency", x)
    }),
    scenario = "zero_mitigation",
    interval = rep(list(interval = c(1L, 1L)), nrow(tpma_data))
  ) |>
  tidyr::nest(.by = "scenario") |>
  tibble::deframe()
```

```{r}
#| label: export data

readr::write_rds(zero_mitigation_tpma_data, rds_fname)

success <- file.exists(rds_fname) && tools::file_ext(rds_fname) == "rds"
succ_msg <- glue::glue("File `{rds_fname}` has been created")
```

`r if (success) succ_msg`

Names of tables in `zero_mitigation_tpma_data` (object saved to rds):

(should be just "zero_mitigation")

```{r}
names(zero_mitigation_tpma_data)
```
